name: yc_flutter_utils
description: A new Flutter project.
version: 0.0.1
author: yangchong<yangchong211@gmail.com>
homepage: https://github.com/yangchong211


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://github.com/a14n/dart-decimal
  decimal: "0.3.5"
  # https://github.com/dart-lang/crypto
  crypto: "2.1.5"
  # https://github.com/dart-lang/convert
  convert: "2.1.1"
  http: '>=0.11.3+12'
  path_provider: ^1.6.9
  cached_network_image: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.utils.yc_flutter_utils
        pluginClass: YcFlutterUtilsPlugin
      ios:
        pluginClass: YcFlutterUtilsPlugin
